### PR TITLE
deps: update to binrw 0.12

### PR DESCRIPTION
**Pull request by poliorcetics**
This updates the MSRV to 1.66, that's maybe too big a leap ?

### CODE REVIEW

**Review by ColinFinck — COMMENTED** [review]
I'm not opposed to dependency upgrades, even if they increase the MSRV.
But looking at binrw 0.12, I fail to see:

* Where does it change MSRV to 1.66? I see such a change for `master`, but not for the 0.12.0 release.
* What has actually changed between 0.11 and 0.12? I don't find the usual `CHANGELOG.md`.
* Is there a specific reason why you need binrw 0.12 instead of 0.11?

CC @jam1garner

**Comment by poliorcetics** [comment]
> Where does it change MSRV to 1.66? I see such a change for master, but not for the 0.12.0 release.

Ah I think I checked master and not 0.12, my bad

> What has actually changed between 0.11 and 0.12? I don't find the usual CHANGELOG.md.

https://github.com/jam1garner/binrw/releases/tag/v0.12.0

> Is there a specific reason why you need binrw 0.12 instead of 0.11?

Just keeping up to date with dependencies and trying to reduces projects' trees to a single instance of each, to avoid compiling almost the same code several times. It also has the benefit that if a type from a dependency is exposed in the public API, it's the same everywhere (because `crateA::MyType, v0.3.0` and `crateA::MyType, v0.4.0` are incompatible)

**Comment by ColinFinck** [comment]
> > Where does it change MSRV to 1.66? I see such a change for master, but not for the 0.12.0 release.
> 
> Ah I think I checked master and not 0.12, my bad

Alright. Can you change the MSRV to the right Rust version for binrw 0.12 then?

**Comment by poliorcetics** [comment]
I forgot I had changed it in the manifest, done

**Pull request merged**
